version: '2'
services:
    pocmonolith-app:
        image: pocmonolith
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://pocmonolith-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=pocMonolith
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pocmonolith-mongodb:
        extends:
            file: mongodb.yml
            service: pocmonolith-mongodb
